In [25]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
data = load_iris()

In [5]:
type(data)

sklearn.utils.Bunch

In [6]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [8]:
feature = data['data']
feature.shape

(150, 4)

In [9]:
target = data['target']
target.shape

(150,)

In [10]:
type(feature)

numpy.ndarray

In [11]:
print(feature)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
print(target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
print(data['target_names'])

['setosa' 'versicolor' 'virginica']


In [14]:
print(data['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [15]:
print(data['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [16]:
print(data['filename'])

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/datasets/data/iris.csv


In [21]:
featurePd = pd.DataFrame(feature)
featurePd.isnull().sum()

0    0
1    0
2    0
3    0
dtype: int64

In [22]:
targetPd = pd.DataFrame(target)
targetPd.isnull().sum()

0    0
dtype: int64

In [26]:
X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.3, random_state=0)##数据集的划分

In [27]:
stdsc = StandardScaler()#实例化
X_train_conti_std = stdsc.fit_transform(X_train)
X_test_conti_std = stdsc.fit_transform(X_test)

In [29]:
print(X_test_conti_std)

[[ 0.10652036 -0.6802299   0.90797473  1.77175914]
 [ 0.39703042 -2.10396689  0.24507283 -0.18650096]
 [-0.32924474  2.64182309 -1.32178623 -1.30550673]
 [ 2.28534586 -0.4429404   1.63114045  0.93250481]
 [-1.05551991  0.7435071  -1.26152242 -1.30550673]
 [ 0.83279553  0.5062176   1.45034902  1.91163486]
 [-1.05551991  0.9807966  -1.38205004 -1.16563101]
 [ 1.41381566  0.0316386   0.66691949  0.51287764]
 [ 1.55907069 -0.6802299   0.7271833   0.37300192]
 [ 0.54228546 -0.6802299   0.24507283  0.2331262 ]
 [ 0.54228546 -1.15480889  1.20929378  0.37300192]
 [ 0.97805056  0.2689281   0.54639188  0.51287764]
 [ 0.54228546 -0.6802299   0.66691949  0.09325048]
 [ 1.12330559 -0.6802299   0.60665568  0.51287764]
 [ 0.54228546 -0.4429404   0.66691949  0.37300192]
 [-1.20077494  1.21808609 -1.32178623 -1.44538245]
 [ 0.39703042 -0.4429404   0.54639188  0.51287764]
 [-0.32924474 -1.15480889  0.48612807  0.09325048]
 [-1.34602998 -0.2056509  -1.32178623 -1.16563101]
 [-0.47449978  1.92995459 -1.38

In [28]:
print(X_train_conti_std)

[[-1.02366372 -2.37846268 -0.18295039 -0.29318114]
 [ 0.69517462 -0.10190314  0.93066067  0.7372463 ]
 [ 0.92435306  0.58106472  1.04202177  1.63887031]
 [ 0.1222285  -1.92315077  0.6522579   0.35083601]
 [ 0.92435306 -1.24018291  1.09770233  0.7372463 ]
 [-0.33612839 -1.24018291  0.03977182 -0.16437771]
 [ 2.07024529 -0.10190314  1.26474398  1.38126345]
 [ 0.46599617  0.58106472  0.48521625  0.47963944]
 [-0.45071761 -1.46783886 -0.01590873 -0.16437771]
 [ 0.46599617 -0.784871    0.59657735  0.7372463 ]
 [ 0.46599617 -0.55721505  0.70793846  0.35083601]
 [-1.13825295 -1.24018291  0.37385514  0.60844287]
 [ 0.46599617 -1.24018291  0.6522579   0.86604973]
 [ 1.26812073  0.35340877  0.48521625  0.22203258]
 [ 0.69517462 -0.10190314  0.76361901  0.99485316]
 [ 0.1222285   0.80872067  0.37385514  0.47963944]
 [-1.25284217  0.12575281 -1.24088089 -1.32360858]
 [-0.10694994 -0.784871    0.70793846  0.86604973]
 [-0.33612839 -0.784871    0.20681348  0.09322915]
 [-0.33612839 -0.32955909 -0.12

In [30]:
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(random_state=0)#实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
confusion_matrix = confusion_matrix(y_test, y_pred)#打印混淆矩阵，是很多评分函数的标准来源
print(confusion_matrix)#打印混淆矩阵

[[16  0  0]
 [ 0 13  5]
 [ 0  0 11]]


/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [31]:
classifier.score(X_test, y_test)

0.8888888888888888

In [34]:
#基于训练集使用逻辑回归建模
classifierStd = LogisticRegression(random_state=0)#实例化算法
classifierStd.fit(X_train_conti_std, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifierStd.predict(X_test_conti_std)#预测

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [35]:
classifier.score(X_test_conti_std, y_test)

0.7777777777777778

In [36]:
featureTwo = feature[:, :2]

In [37]:
print(featureTwo)

[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.  3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3. ]
 [4.3 3. ]
 [5.8 4. ]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.  3. ]
 [5.  3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 3.2]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.  3.2]
 [5.5 3.5]
 [4.9 3.6]
 [4.4 3. ]
 [5.1 3.4]
 [5.  3.5]
 [4.5 2.3]
 [4.4 3.2]
 [5.  3.5]
 [5.1 3.8]
 [4.8 3. ]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.  3.3]
 [7.  3.2]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [5.2 2.7]
 [5.  2. ]
 [5.9 3. ]
 [6.  2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3. ]
 [5.8 2.7]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [6.1 2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3. ]
 [6.8 2.8]
 [6.7 3. ]
 [6.  2.9]
 [5.7 2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.  2.7]
 [5.4 3. ]
 [6.  3.4]
 [6.7 3.1]
 [6.3 2.3]
 [5.6 3. ]
 [5.5 2.5]
 [5.5 2.6]

In [38]:
X_train, X_test, y_train, y_test = train_test_split(featureTwo, target, test_size=0.2, random_state=0)##数据集的划分

In [40]:
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(random_state=0)#实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [41]:
classifier.score(X_test, y_test)

0.6

In [42]:
featureTmp = feature[:, [0,2]]

In [43]:
print(featureTmp)

[[5.1 1.4]
 [4.9 1.4]
 [4.7 1.3]
 [4.6 1.5]
 [5.  1.4]
 [5.4 1.7]
 [4.6 1.4]
 [5.  1.5]
 [4.4 1.4]
 [4.9 1.5]
 [5.4 1.5]
 [4.8 1.6]
 [4.8 1.4]
 [4.3 1.1]
 [5.8 1.2]
 [5.7 1.5]
 [5.4 1.3]
 [5.1 1.4]
 [5.7 1.7]
 [5.1 1.5]
 [5.4 1.7]
 [5.1 1.5]
 [4.6 1. ]
 [5.1 1.7]
 [4.8 1.9]
 [5.  1.6]
 [5.  1.6]
 [5.2 1.5]
 [5.2 1.4]
 [4.7 1.6]
 [4.8 1.6]
 [5.4 1.5]
 [5.2 1.5]
 [5.5 1.4]
 [4.9 1.5]
 [5.  1.2]
 [5.5 1.3]
 [4.9 1.4]
 [4.4 1.3]
 [5.1 1.5]
 [5.  1.3]
 [4.5 1.3]
 [4.4 1.3]
 [5.  1.6]
 [5.1 1.9]
 [4.8 1.4]
 [5.1 1.6]
 [4.6 1.4]
 [5.3 1.5]
 [5.  1.4]
 [7.  4.7]
 [6.4 4.5]
 [6.9 4.9]
 [5.5 4. ]
 [6.5 4.6]
 [5.7 4.5]
 [6.3 4.7]
 [4.9 3.3]
 [6.6 4.6]
 [5.2 3.9]
 [5.  3.5]
 [5.9 4.2]
 [6.  4. ]
 [6.1 4.7]
 [5.6 3.6]
 [6.7 4.4]
 [5.6 4.5]
 [5.8 4.1]
 [6.2 4.5]
 [5.6 3.9]
 [5.9 4.8]
 [6.1 4. ]
 [6.3 4.9]
 [6.1 4.7]
 [6.4 4.3]
 [6.6 4.4]
 [6.8 4.8]
 [6.7 5. ]
 [6.  4.5]
 [5.7 3.5]
 [5.5 3.8]
 [5.5 3.7]
 [5.8 3.9]
 [6.  5.1]
 [5.4 4.5]
 [6.  4.5]
 [6.7 4.7]
 [6.3 4.4]
 [5.6 4.1]
 [5.5 4. ]
 [5.5 4.4]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(featureTmp, target, test_size=0.2, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(random_state=0)#实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [45]:
classifier.score(X_test, y_test)

0.8333333333333334

In [46]:
featureTmp2 = feature[:, [2,3]]

In [47]:
X_train, X_test, y_train, y_test = train_test_split(featureTmp2, target, test_size=0.2, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(random_state=0)#实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
classifier.score(X_test, y_test)

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7

In [48]:
featureTmp3 = feature[:, [0,3]]
X_train, X_test, y_train, y_test = train_test_split(featureTmp3, target, test_size=0.3, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(random_state=0)#实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
classifier.score(X_test, y_test)

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7555555555555555

In [49]:
X_train, X_test, y_train, y_test = train_test_split(featureTmp2, target, test_size=0.3, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(random_state=0)#实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
classifier.score(X_test, y_test)

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.6888888888888889

In [51]:
stdsc = StandardScaler()#实例化
featureStd = stdsc.fit_transform(feature)

In [52]:
X_train, X_test, y_train, y_test = train_test_split(featureStd, target, test_size=0.2, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(random_state=0)#实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
classifier.score(X_test, y_test)

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.8666666666666667

In [53]:
featureTmp3 = feature[:, [0,2]]
X_train, X_test, y_train, y_test = train_test_split(featureTmp2, target, test_size=0.2, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(C=1e5) #实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
classifier.score(X_test, y_test) 

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9666666666666667

In [54]:
X_train, X_test, y_train, y_test = train_test_split(featureTmp3, target, test_size=0.2, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(C=1e5) #实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
classifier.score(X_test, y_test) 

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9666666666666667

In [55]:
X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.2, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(C=1e5) #实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
classifier.score(X_test, y_test) 

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


1.0

In [56]:
X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.3, random_state=0)##数据集的划分
#基于训练集使用逻辑回归建模
classifier = LogisticRegression(C=1e5) #实例化算法
classifier.fit(X_train, y_train)#模型训练
# 将模型应用于测试集并查看混淆矩阵
y_pred = classifier.predict(X_test)#预测
classifier.score(X_test, y_test) 

/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/didi/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9777777777777777